baseURL = 'http://holdenthomas.xyz/'
languageCode = 'en-us'
title = "Holden's Website"
theme = "PaperMod"

[params]
    keywords = ["Blog","Portfolio","PaperMod"]
    author = ["Holden"]
    DateFormat = "January 2, 2006"
    defaultTheme = "auto"
    ShowBreadCrumbs = true
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowCodeCopyButtons = true
    ShowWordCount = true
    ShowRssButtonInSectionTermList = true
    showtoc = true
    [params.assets]
        favicon = "/favicon.ico"
        favicon16x16 = "/favicon.ico"
        favicon32x32 = "/favicon.ico"
        apple_touch_icon = "/favicon.ico"
        safari_pinned_tab = "/favicon.ico"
    [params.cover]
        linkFullImages = true
    [params.homeInfoParams]
        title = "Hey, What's Up"
        content = """Welcome to my website! Just some stuff here.

Random website created by someone named Holden, idk?"""
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/holdenthomas"
    [[params.socialIcons]]
        name = "rss"
        url = "index.xml"

[menu]
    [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories"
        weight = 10
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags"
        weight = 20
    [[menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "/archives"
        weight = 30
